version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aibf_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d aibf_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGDATABASE=aibf_db
      - PGUSER=root
      - PGPASSWORD=pass
      - PGHOST=db
      - PGPORT=5432

volumes:
  postgres_data: